---
- name: Instalar paquetes y desplegar aplicación
  hosts: web
  become: yes

  tasks:
    - name: Actualizar caché de paquetes
      apt:
        update_cache: yes

    - name: Instalar git, npm y nginx
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - npm
        - nginx

    - name: Clonar repositorio de la aplicación
      git:
        repo: "{{ repo }}"
        dest: /var/www/myapp
        version: master

    - name: Instalar dependencias de la aplicación
      command: npm install
      args:
        chdir: /var/www/myapp

    - name: Configurar archivo de host de Nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/myapp
      notify: Reiniciar Nginx

    - name: Activar archivo de host de Nginx
      file:
        src: /etc/nginx/sites-available/myapp
        dest: /etc/nginx/sites-enabled/myapp
        state: link
      notify: Reiniciar Nginx

  handlers:
    - name: Reiniciar Nginx
      service:
        name: nginx
        state: restarted
